lib/watwitter_web/router.ex
defmodule WatwitterWeb.Router do
  use WatwitterWeb, :router

  import WatwitterWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {WatwitterWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", WatwitterWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/", TimelineLive, :index
    live "/compose", ComposeLive, :new
  end

  # Other scopes may use custom stacks.
  # scope "/api", WatwitterWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: WatwitterWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", WatwitterWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", WatwitterWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings/update_password", UserSettingsController, :update_password
    put "/users/settings/update_email", UserSettingsController, :update_email
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", WatwitterWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/watwitter_web/controllers/user_registration_controller.ex
defmodule WatwitterWeb.UserRegistrationController do
  use WatwitterWeb, :controller

  alias Watwitter.Accounts
  alias Watwitter.Accounts.User
  alias WatwitterWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :confirm, &1)
          )

        UserAuth.log_in_user(conn, user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/watwitter_web/views/user_registration_view.ex
defmodule WatwitterWeb.UserRegistrationView do
  use WatwitterWeb, :view
end

lib/watwitter_web/templates/user_registration/new.html.eex
<div class="header">
  <h1 class="header-title">Register</h1>
</div>

<div class="form-wrapper">
  <%= form_for @changeset, Routes.user_registration_path(@conn, :create), [class: "form"], fn f -> %>
      <%= if @changeset.action do %>
        <div class="alert alert-danger">
          <p>Oops, something went wrong! Please check the errors below.</p>
        </div>
      <% end %>

    <div class="form-fields">
      <div class="form-field">
        <%= label f, :name, class: "form-label" %>
        <%= text_input f, :name, required: true, class: "form-input field-input" %>
        <%= error_tag f, :name %>
      </div>

      <div class="form-field">
        <%= label f, :username, class: "form-label" %>
        <%= text_input f, :username, required: true, class: "form-input field-input" %>
        <%= error_tag f, :username %>
      </div>

      <div class="form-field">
        <%= label f, :email, class: "form-label" %>
        <%= email_input f, :email, required: true, class: "form-input field-input" %>
        <%= error_tag f, :email %>
      </div>

      <div class="form-field">
        <%= label f, :password, class: "form-label" %>
        <%= password_input f, :password, required: true, class: "form-input field-input" %>
        <%= error_tag f, :password %>
      </div>

      <div class="form-action">
        <%= submit "Register", class: "btn btn-full" %>
      </div>
    </div>
  <% end %>
</div>

<footer class="footer">
  <p class="footer-links">
    <%= link "Log in", to: Routes.user_session_path(@conn, :new) %> |
    <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new) %>
  </p>
</footer>